default_language_version:
  python: python3.7
repos:
  - repo: https://git.tianrang-inc.com/mirrors/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://git.tianrang-inc.com/mirrors/isort
    rev: 5.9.2
    hooks:
      - id: isort
        language_version: python3
  - repo: https://git.tianrang-inc.com/mirrors/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: double-quote-string-fixer
  - repo: local
    hooks:
    - id: pylint
      name: pylint - Source - Errors
      entry: pylint -E -j 2 -f colorized --persistent=no --reports=no --score=no
      types: [python]
      language: python
