#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import json
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--lang', default='python3')
parser.add_argument('--model-json',)
args = parser.parse_args()


from lgb_convertor import e2e_convert


def main():
    model_json = json.load(open(args.model_json))
    print(e2e_convert(model_json, args.lang))


if __name__ == '__main__':
    main()
