#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import json
import os
import pathlib
import sys

from lgb_convertor import __version__, e2e_convert

parser = argparse.ArgumentParser(
    description="""

Description:
============
lgbc is a tool that convert LightGBM(aka lgb) model to
    if-else statements of each language. \n

Examples:
=========
- lgbc --model-json example/test_model_tiny.json --lang python3
- lgbc -m example/test_model_tiny.json -l cpp

See more at [https://github.com/Yangruipis/lgb-convertor]

""",
    formatter_class=argparse.RawTextHelpFormatter,
)
parser.add_argument('--lang', '-l', default='python3', type=str, help='language to convert')
parser.add_argument(
    '--model-json',
    '-m',
    type=pathlib.Path,
    required=True,
    help='lightgbm model json, dumped by `lgb_model.booster_.dump_model()`',
)
parser.add_argument('-v', '--version', action='version', version='lgbc==v%s' % __version__)
args = parser.parse_args()


def main():
    model_json = json.load(open(args.model_json))
    print(e2e_convert(model_json, args.lang))


if __name__ == '__main__':
    main()
