// 
// 
// THIS CODE IS GENERATED BY lgb-convertor. DO NOT EDIT IT.
// 
// https://github.com/Yangruipis/lgb-convertor
// 
// MIT License
// 
// Copyright (c) 2021 r.yang
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 

#include <cmath>

float predict_tree_0(float* arr)
{

    if (std::abs(arr[4] - 0) <= 1e-6 || std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
    {
        
        if ( std::isnan(arr[10]) || ( arr[10] <= -0.4660354475469295 ) )
        {
            
            if ( arr[10] <= -0.6335825668312044 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.059589550055924 ) )
                {
                    return -0.20960576304039685;
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -0.8356046362200794 ) )
                    {
                        return -0.17150944181281869;
                    }
                    else
                    {
                        return -0.19293862250333133;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.6335825668312044 ) )
                {
                    return -0.14131113840071408;
                }
                else
                {
                    return -0.15246128119902963;
                }
            }
        }
        else
        {
            
            if ( arr[4] == 2 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.1237481842214978 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.10263676483623875 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -0.11160308663139516 ) )
                        {
                            return 0.1358586044551413;
                        }
                        else
                        {
                            return 0.17040504120469507;
                        }
                    }
                    else
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.6229355371163823 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.41658880621098043 ) )
                            {
                                return 0.036555081814723465;
                            }
                            else
                            {
                                return 0.01040049204886695;
                            }
                        }
                        else
                        {
                            return 0.07275520605812354;
                        }
                    }
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                    {
                        return -0.1368764225150204;
                    }
                    else
                    {
                        return -0.19221396421911113;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 0.7204562067911064 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -0.09622749118588046 ) )
                    {
                        return -0.18960519439591828;
                    }
                    else
                    {
                        return -0.2096057630403968;
                    }
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.2327612561131984 ) )
                    {
                        return -0.1696046257514398;
                    }
                    else
                    {
                        return -0.17150944181281869;
                    }
                }
            }
        }
    }
    else
    {
        
        if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -2.0984932026194723 ) )
            {
                
                if ( arr[10] <= -2.281569461139397 )
                {
                    return 0.08131159906110898;
                }
                else
                {
                    return 0.09809529302850352;
                }
            }
            else
            {
                return 0.03387942045760261;
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= 1.808253511876131 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.0600466412777372 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= -0.38382561511263785 ) )
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= -0.923662743837944 ) )
                                {
                                    return 0.15319524958037645;
                                }
                                else
                                {
                                    return 0.17864056947006857;
                                }
                            }
                            else
                            {
                                return 0.13040390391573803;
                            }
                        }
                        else
                        {
                            return 0.1904056098491737;
                        }
                    }
                    else
                    {
                        return 0.13326112800780648;
                    }
                }
                else
                {
                    return 0.17611948938883187;
                }
            }
            else
            {
                return 0.09040276662678105;
            }
        }
    }
}


float predict_tree_1(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        return -0.11058631598294409;
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            return -0.005831185133627415;
        }
        else
        {
            return 0.13227030947182297;
        }
    }
}


float predict_tree_2(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[10] <= -0.43594116203149386 )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -1.383951587021315 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
                {
                    return -0.1813982436788787;
                }
                else
                {
                    return -0.17414946669796524;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.7076986948308028 ) )
                {
                    
                    if ( arr[10] <= -0.923662743837944 )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.1569265931216723 ) )
                        {
                            return -0.13829649029219934;
                        }
                        else
                        {
                            return -0.17514184003491473;
                        }
                    }
                    else
                    {
                        return -0.133584587844517;
                    }
                }
                else
                {
                    return -0.17542810168134315;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 0.10263676483623875 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                {
                    return -0.03677376236348131;
                }
                else
                {
                    return -0.0034900155467758043;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.092949497193538 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.6843435789688959 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.270354883367074 ) )
                        {
                            return -0.11315268242148907;
                        }
                        else
                        {
                            return -0.08163860825586752;
                        }
                    }
                    else
                    {
                        return -0.039931530165560516;
                    }
                }
                else
                {
                    return -0.13760671650183717;
                }
            }
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            
            if ( arr[10] <= 1.1117274256022427 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3412048036785434 ) )
                {
                    return -0.028004126657844526;
                }
                else
                {
                    
                    if ( arr[10] <= 0.5372481771262306 )
                    {
                        
                        if ( arr[10] <= 0.10263676483623875 )
                        {
                            return 0.15094217000840382;
                        }
                        else
                        {
                            return 0.10792113907024262;
                        }
                    }
                    else
                    {
                        return 0.057675475403559655;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                {
                    return -0.10593729612110776;
                }
                else
                {
                    return -0.1666991563682367;
                }
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -2.281569461139397 ) )
            {
                
                if ( arr[10] <= -2.281569461139397 )
                {
                    return 0.0844402466714775;
                }
                else
                {
                    return 0.1128132602841471;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.8557995136266112 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -0.6023105644130694 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= -1.7424948485867422 ) )
                            {
                                return 0.14450369795918114;
                            }
                            else
                            {
                                
                                if ( arr[10] <= -1.0371532198477444 )
                                {
                                    return 0.17567417563311571;
                                }
                                else
                                {
                                    return 0.1563685092481056;
                                }
                            }
                        }
                        else
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 0.3170894232047965 ) )
                                {
                                    return 0.14394857820055632;
                                }
                                else
                                {
                                    return 0.12031406378743986;
                                }
                            }
                            else
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 1.0600466412777372 ) )
                                {
                                    return 0.17242085166027304;
                                }
                                else
                                {
                                    return 0.12970765787157654;
                                }
                            }
                        }
                    }
                    else
                    {
                        return 0.17346289109538385;
                    }
                }
                else
                {
                    return 0.09199876583429574;
                }
            }
        }
    }
}


float predict_tree_3(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[10] <= -0.43594116203149386 )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -1.383951587021315 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
                {
                    return -0.16799389024326128;
                }
                else
                {
                    return -0.16233727538267623;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.7076986948308028 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -0.923662743837944 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.1569265931216723 ) )
                        {
                            return -0.12750377271657756;
                        }
                        else
                        {
                            return -0.1631014709571338;
                        }
                    }
                    else
                    {
                        return -0.12328547567280126;
                    }
                }
                else
                {
                    return -0.1632936721673602;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 0.10263676483623875 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                {
                    return -0.03317862586648204;
                }
                else
                {
                    return -0.0031417782606023258;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.092949497193538 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.6843435789688959 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.270354883367074 ) )
                        {
                            return -0.10350277405644648;
                        }
                        else
                        {
                            return -0.07411529560440179;
                        }
                    }
                    else
                    {
                        return -0.03608615661442632;
                    }
                }
                else
                {
                    return -0.12654974899719193;
                }
            }
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            
            if ( arr[10] <= 1.1117274256022427 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3412048036785434 ) )
                {
                    return -0.02525420499864099;
                }
                else
                {
                    
                    if ( arr[10] <= 0.5372481771262306 )
                    {
                        
                        if ( arr[10] <= 0.10263676483623875 )
                        {
                            return 0.13794510004553803;
                        }
                        else
                        {
                            return 0.09749163516055268;
                        }
                    }
                    else
                    {
                        return 0.052015368700347425;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                {
                    return -0.09640425984733908;
                }
                else
                {
                    return -0.15371024085001478;
                }
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -2.281569461139397 ) )
            {
                
                if ( arr[10] <= -2.281569461139397 )
                {
                    return 0.07686000315670172;
                }
                else
                {
                    return 0.10319961689864368;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.8557995136266112 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -0.6023105644130694 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= -1.7424948485867422 ) )
                            {
                                return 0.1326249336048868;
                            }
                            else
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= -1.0371532198477444 ) )
                                {
                                    return 0.16348654160137935;
                                }
                                else
                                {
                                    return 0.14522101180685226;
                                }
                            }
                        }
                        else
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 0.3170894232047965 ) )
                                {
                                    return 0.13290942813903536;
                                }
                                else
                                {
                                    return 0.11038190315283668;
                                }
                            }
                            else
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 1.0600466412777372 ) )
                                {
                                    return 0.16095119772119704;
                                }
                                else
                                {
                                    return 0.11937199739824561;
                                }
                            }
                        }
                    }
                    else
                    {
                        return 0.1617638064386444;
                    }
                }
                else
                {
                    return 0.08387592148311525;
                }
            }
        }
    }
}


float predict_tree_4(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[8] == 2 )
        {
            return -0.02333255394798686;
        }
        else
        {
            return -0.11147437700861683;
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            return -0.0044751088557765314;
        }
        else
        {
            return 0.10403644673989583;
        }
    }
}


float predict_tree_5(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[10] <= -0.43594116203149386 )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -1.383951587021315 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
                {
                    return -0.1557191149069707;
                }
                else
                {
                    return -0.1508271483527971;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.7076986948308028 ) )
                {
                    
                    if ( arr[10] <= -0.923662743837944 )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.1569265931216723 ) )
                        {
                            return -0.11463115539164588;
                        }
                        else
                        {
                            return -0.14833176591863306;
                        }
                    }
                    else
                    {
                        return -0.10756859531330767;
                    }
                }
                else
                {
                    return -0.14808965025309503;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 0.10263676483623875 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                {
                    return -0.022510441180365402;
                }
                else
                {
                    return 0.0045936931491726155;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.092949497193538 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.6843435789688959 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.270354883367074 ) )
                        {
                            return -0.08864121036416671;
                        }
                        else
                        {
                            return -0.06180377517895801;
                        }
                    }
                    else
                    {
                        return -0.02509486352421037;
                    }
                }
                else
                {
                    return -0.11024870424730249;
                }
            }
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            
            if ( arr[10] <= 1.1117274256022427 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3412048036785434 ) )
                {
                    return -0.02233917631718703;
                }
                else
                {
                    
                    if ( arr[10] <= 0.5372481771262306 )
                    {
                        
                        if ( arr[10] <= 0.10263676483623875 )
                        {
                            return 0.12753073470973583;
                        }
                        else
                        {
                            return 0.08890739757649001;
                        }
                    }
                    else
                    {
                        return 0.04740354019568921;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                {
                    return -0.0877079991072886;
                }
                else
                {
                    return -0.14297121404967464;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 2.9774316303874753 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -2.281569461139397 ) )
                {
                    return 0.061140984046805985;
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.8557995136266112 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= -0.6023105644130694 ) )
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7424948485867422 ) )
                                {
                                    return 0.11539838239893599;
                                }
                                else
                                {
                                    return 0.14140571898909554;
                                }
                            }
                            else
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                                {
                                    return 0.10628484874527047;
                                }
                                else
                                {
                                    return 0.12444758947651252;
                                }
                            }
                        }
                        else
                        {
                            return 0.14734765464532493;
                        }
                    }
                    else
                    {
                        return 0.09966863690083452;
                    }
                }
            }
            else
            {
                return 0.05933542841659728;
            }
        }
    }
}


float predict_tree_6(float* arr)
{

    if (std::abs(arr[4] - 0) <= 1e-6 || std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
    {
        
        if ( arr[4] == 2 )
        {
            
            if ( arr[0] == 2 )
            {
                return 0.028221009296235774;
            }
            else
            {
                return -0.03670399936142792;
            }
        }
        else
        {
            return -0.11157587767563515;
        }
    }
    else
    {
        return 0.07989734575142823;
    }
}


float predict_tree_7(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[10] <= -0.43594116203149386 )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -1.383951587021315 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
                {
                    return -0.1490578634708877;
                }
                else
                {
                    return -0.1424919995125706;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.7076986948308028 ) )
                {
                    
                    if ( arr[10] <= -0.923662743837944 )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.1569265931216723 ) )
                        {
                            return -0.1059039329596867;
                        }
                        else
                        {
                            return -0.13899508647339173;
                        }
                    }
                    else
                    {
                        return -0.0955704036389853;
                    }
                }
                else
                {
                    return -0.1374943911550264;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 0.10263676483623875 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                {
                    return -0.01610173249139348;
                }
                else
                {
                    return 0.011039621766562544;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.092949497193538 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.6843435789688959 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.270354883367074 ) )
                        {
                            return -0.0778805774198904;
                        }
                        else
                        {
                            return -0.052003051892324154;
                        }
                    }
                    else
                    {
                        return -0.01520138486665834;
                    }
                }
                else
                {
                    return -0.0988677898215192;
                }
            }
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            
            if ( arr[10] <= 1.1117274256022427 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3412048036785434 ) )
                {
                    return -0.016314460070226692;
                }
                else
                {
                    
                    if ( arr[10] <= 0.5372481771262306 )
                    {
                        
                        if ( arr[10] <= 0.10263676483623875 )
                        {
                            return 0.11831505563367167;
                        }
                        else
                        {
                            return 0.0796732893879585;
                        }
                    }
                    else
                    {
                        return 0.041724422036999886;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                {
                    return -0.0803618949097972;
                }
                else
                {
                    return -0.13483114043041414;
                }
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -1.9134626092537608 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -2.5054508153843327 ) )
                {
                    return 0.08396048071273823;
                }
                else
                {
                    return 0.039909728950061375;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.8557995136266112 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -1.0371532198477444 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.5340216560111244 ) )
                        {
                            return 0.14199199873975982;
                        }
                        else
                        {
                            return 0.1386754289441012;
                        }
                    }
                    else
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                        {
                            
                            if ( arr[10] <= 1.0600466412777372 )
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                                {
                                    return 0.10266718305064604;
                                }
                                else
                                {
                                    return 0.13812007223412734;
                                }
                            }
                            else
                            {
                                return 0.08949133163748446;
                            }
                        }
                        else
                        {
                            return 0.13772308057480318;
                        }
                    }
                }
                else
                {
                    return 0.05337495210391883;
                }
            }
        }
    }
}


float predict_tree_8(float* arr)
{

    if (std::abs(arr[4] - 0) <= 1e-6 || std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
    {
        
        if ( arr[4] == 2 )
        {
            
            if ( arr[10] <= -0.7473412710926279 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.1712896179918242 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -1.4365260071341865 ) )
                    {
                        return -0.1383516813020625;
                    }
                    else
                    {
                        return -0.14302099190605386;
                    }
                }
                else
                {
                    return -0.09502712817297794;
                }
            }
            else
            {
                
                if ( arr[10] <= 1.1117274256022427 )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.10263676483623875 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                        {
                            return 0.10682539573347022;
                        }
                        else
                        {
                            return 0.15679155283633056;
                        }
                    }
                    else
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.6229355371163823 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.3748056188087266 ) )
                            {
                                return 0.02894291380869553;
                            }
                            else
                            {
                                return 0.04701084370766996;
                            }
                        }
                        else
                        {
                            return 0.0754333911400075;
                        }
                    }
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 1.1237481842214978 ) )
                        {
                            return -0.03260443648956659;
                        }
                        else
                        {
                            return -0.07882502163417088;
                        }
                    }
                    else
                    {
                        return -0.1257778360770971;
                    }
                }
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= 0.7204562067911064 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3690574538145624 ) )
                {
                    
                    if ( arr[10] <= -0.38382561511263785 )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -0.6335825668312044 ) )
                        {
                            return -0.1359811658702619;
                        }
                        else
                        {
                            return -0.1411558000161;
                        }
                    }
                    else
                    {
                        return -0.10537791038473752;
                    }
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.12324299681620544 ) )
                    {
                        return -0.16828803503385004;
                    }
                    else
                    {
                        return -0.14851383238904511;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.2327612561131984 ) )
                {
                    return -0.1090137935891782;
                }
                else
                {
                    return -0.09142096776529371;
                }
            }
        }
    }
    else
    {
        
        if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= -2.5054508153843327 ) )
            {
                return 0.06374222947382167;
            }
            else
            {
                return 0.015589050012918541;
            }
        }
        else
        {
            
            if ( std::isnan(arr[10]) || ( arr[10] <= 1.808253511876131 ) )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.0371532198477444 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -1.3666980354959293 ) )
                    {
                        return 0.12302699514147325;
                    }
                    else
                    {
                        return 0.12198018651102466;
                    }
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 1.2666113830780408 ) )
                    {
                        
                        if ( arr[10] <= 1.0344378468451094 )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                            {
                                
                                if ( arr[10] <= 0.2871349487504708 )
                                {
                                    return 0.10194435961471378;
                                }
                                else
                                {
                                    return 0.07140134539513462;
                                }
                            }
                            else
                            {
                                return 0.1332023478017826;
                            }
                        }
                        else
                        {
                            return 0.07190491431686517;
                        }
                    }
                    else
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 1.544554910089751 ) )
                        {
                            return 0.11949362068864343;
                        }
                        else
                        {
                            return 0.1141041039597952;
                        }
                    }
                }
            }
            else
            {
                return 0.0397519826947082;
            }
        }
    }
}


float predict_tree_9(float* arr)
{

    if (std::abs(arr[0] - 3) <= 1e-6 || std::abs(arr[0] - 4) <= 1e-6)
    {
        
        if ( arr[10] <= -0.43594116203149386 )
        {
            
            if ( arr[10] <= -1.383951587021315 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -1.7146519439798416 ) )
                {
                    return -0.14081093481540077;
                }
                else
                {
                    return -0.13316247036227646;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.7076986948308028 ) )
                {
                    
                    if ( arr[10] <= -0.923662743837944 )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.1569265931216723 ) )
                        {
                            return -0.09467936856900803;
                        }
                        else
                        {
                            return -0.13093140058474081;
                        }
                    }
                    else
                    {
                        return -0.0832614549775123;
                    }
                }
                else
                {
                    return -0.12976950537868656;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 0.10263676483623875 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.19006063362567147 ) )
                {
                    return -0.014965114400122307;
                }
                else
                {
                    return 0.010267289654199626;
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.092949497193538 ) )
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= 0.6843435789688959 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.3464011453669733 ) )
                        {
                            
                            if ( arr[10] <= 0.3170894232047965 )
                            {
                                return -0.08029568933019529;
                            }
                            else
                            {
                                return -0.03327689846637425;
                            }
                        }
                        else
                        {
                            return -0.07894447023460922;
                        }
                    }
                    else
                    {
                        return -0.011276808568408733;
                    }
                }
                else
                {
                    return -0.08931919594490245;
                }
            }
        }
    }
    else
    {
        
        if (std::abs(arr[4] - 1) <= 1e-6 || std::abs(arr[4] - 2) <= 1e-6)
        {
            
            if ( arr[10] <= 1.1117274256022427 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -0.3412048036785434 ) )
                {
                    return -0.010131080934297808;
                }
                else
                {
                    
                    if ( arr[10] <= 0.5372481771262306 )
                    {
                        
                        if ( arr[10] <= 0.10263676483623875 )
                        {
                            return 0.10417634519522777;
                        }
                        else
                        {
                            return 0.07076425475138097;
                        }
                    }
                    else
                    {
                        return 0.032512375437444334;
                    }
                }
            }
            else
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= 1.5908341551884078 ) )
                {
                    return -0.0683188326774171;
                }
                else
                {
                    return -0.12134168184597943;
                }
            }
        }
        else
        {
            
            if ( arr[10] <= 2.9774316303874753 )
            {
                
                if ( std::isnan(arr[10]) || ( arr[10] <= -2.281569461139397 ) )
                {
                    return 0.03875687738358662;
                }
                else
                {
                    
                    if ( std::isnan(arr[10]) || ( arr[10] <= -0.6023105644130694 ) )
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= -1.7424948485867422 ) )
                        {
                            return 0.09747998108395357;
                        }
                        else
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= -1.0371532198477444 ) )
                            {
                                return 0.1301899074054485;
                            }
                            else
                            {
                                return 0.10927488828895496;
                            }
                        }
                    }
                    else
                    {
                        
                        if ( std::isnan(arr[10]) || ( arr[10] <= 0.8232673391312045 ) )
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 0.3170894232047965 ) )
                            {
                                return 0.09573688314917067;
                            }
                            else
                            {
                                return 0.0703865957709392;
                            }
                        }
                        else
                        {
                            
                            if ( std::isnan(arr[10]) || ( arr[10] <= 1.0600466412777372 ) )
                            {
                                return 0.12935224606937898;
                            }
                            else
                            {
                                
                                if ( std::isnan(arr[10]) || ( arr[10] <= 1.4123288639122298 ) )
                                {
                                    return 0.07782906970075605;
                                }
                                else
                                {
                                    return 0.10510665578425665;
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                return 0.036815657032985886;
            }
        }
    }
}


float predict_tree_all(float* arr)
{
return predict_tree_0(arr) + predict_tree_1(arr) + predict_tree_2(arr) + predict_tree_3(arr) + predict_tree_4(arr) + predict_tree_5(arr) + predict_tree_6(arr) + predict_tree_7(arr) + predict_tree_8(arr) + predict_tree_9(arr);
}


#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>

using namespace std;

float sigmoid(float in) { return 1 / (1.0 + exp(-in)); }

int main()
{
    ifstream is_feat("tests/data/feature.csv");
    ifstream is_pred("tests/data/lgb_predict.csv");
    string str, token, pred;
    string delimiter = ",";
    size_t pos = 0;
    while (getline(is_feat, str))
    {
        getline(is_pred, pred);
        float arr[11];
        int count = 0;
        for (int count = 0; count < 11; count++)
        {
            pos = str.find(delimiter);
            token = str.substr(0, pos);
            str.erase(0, pos + delimiter.length());
            if (token == "nan")
            {
                arr[count] = std::nan("");
            }
            else
            {
                arr[count] = std::stof(token);
            }
            printf("%d %6.6lf\n", count, arr[count]);
        }
        auto res = sigmoid(predict_tree_all(arr));
        auto answer = std::stof(pred);
        printf("%6.4lf vs %6.4lf\n", res, answer);
        if (std::abs(res - answer) > 1e-6)
            throw std::runtime_error("not equal ");
    }
    return 0;
}
