name: JAVA

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: run test
      run: |
        python setup.py install
        python tests/alignment/runner.py --lang java
